Allow maps to fail in CI, but keep going to get latest graphs

diff --git a/.github/workflows/make-images.yml b/.github/workflows/make-images.yml
--- a/.github/workflows/make-images.yml
+++ b/.github/workflows/make-images.yml
@@ -17,13 +17,17 @@ jobs:
         python -m pip install --upgrade pip
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
-    - name: Generate
+    - name: Generate graphs
       run: |
         python prune-cache.py --inplace --days 90 # Re-fetch most recent 90 days, in case of reanalysis
-        python sea-surface-temps.py --mode map --dataset sst --days-ago 1 --out sst-map.png
-        python sea-surface-temps.py --mode map --dataset anom --days-ago 1 --out sst-anom-map.png
         python sea-surface-temps.py --mode all --dataset sst --out sst-all.png
         python sea-surface-temps.py --mode all --dataset anom --out sst-all-anom.png
+
+    # Maps: OK if these fail; we're looking for yesterday, might not be there yet.
+    - name: Generate maps
+      run: |
+        python sea-surface-temps.py --mode map --dataset sst --days-ago 1 --out sst-map.png || true
+        python sea-surface-temps.py --mode map --dataset anom --days-ago 1 --out sst-anom-map.png || true
 
     - name: Get current date
       id: date
